name: bloc_input_valueobject
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.2+2

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  bloc_test: ^9.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  mockito: ^5.4.2
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true